Add solution for MeetupCover
js-tasks-ru/vue-20210304_sidiga pull request #7
Opened 2021-04-27 12:43 UTC by sqadirova

2021-04-27 12:43 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-04-27 15:23 UTC, ShGKme requested changes
С решением всё ок, но требуется обновить репозиторий командой
```git
git pull upstream master
git push origin master
```

2021-04-28 09:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-28 09:43 UTC, ShGKme approved these changes
Принято 👍

2021-04-28 09:43 UTC, merged